### PR TITLE
changes in dependencies.rst to remove cython related issue

### PR DESCRIPTION
**Pull request by skc222**

### CODE REVIEW

**Review by katyhuff — APPROVED** [review]
Looks great. I think this can / should be submitted as a pull request to cyclus/cyclus as a solution to issue1374 !

**Comment by skc222** [comment]
Done!

**Comment by katyhuff** [comment]
Perfect. Now in an ordinary pull request, I would merge this into the repository and we would be done. BUT, this was just a test run because of the nervousness. You now really need to make the pull request against cyclus/cyclus, which is the main fork of the cyclus code. So, I'll close this PR and you should create a new PR from skc222/cyclus (issue1374) to cyclus/cyclus (develop).

**Comment by skc222** [comment]
Yes ma'am. I already made PR from skc222/cyclus (issue1374) to cyclus/cyclus (develop).
Thanks to you for helping me to overcome my nervousness  :dancer:

**Comment by katyhuff** [comment]
Excellent. 
Please next time include a description in the description text. It is the courteous thing to do.

**Comment by skc222** [comment]
Yes sure, I will keep that in mind.

**Pull request closed without merging**
