### PR TITLE
PR: Latest GIS

### PR DESCRIPTION
**Pull request by gyutaepark**
PR for Latest GIS class with:
-test facilities
-tests
-GIS implementation

### CODE REVIEW

**Comment by katyhuff** [comment]
This looks good to me. Are you ready to make this same PR to the real cyclus repository?

**Review by katyhuff — COMMENTED** [review]
I think this is ready for PR against cyclus/cyclus

**Comment by gyutaepark** [comment]
Sounds great! I think I am ready to make this same PR to the real cyclus repository.
Should I make one right now?

**Comment by katyhuff** [comment]
go for it. I'll close this one.

**Pull request closed without merging**
